### ISSUE TITLE
Forks are Excluded

### ISSUE THREAD

**Issue by Justgonc** [nathanielchi/github-profile-readme-statistics#2]
Hi @nathanielchi ,

Many thanks for this great action :)

The action excludes the forked repositories while calculating the stats. I personally think that there are may be forked repositories which may worth to mention in the profile (in terms of count and stars). So, what do you think about stopping to exclude forks?

Or an input can be added to the action to include this kind of repositories.

**Comment by nathanielchi** [comment]
I don't understand what you mean, Please explain.

**Comment by Justgonc** [comment]
Many thanks for the quick reply :).

What I mean is that we should add the include forks section to the source code and action

**Comment by nathanielchi** [comment]
Oh Okay,
Would you like to put up a PR for this?
It would consist of adding an option(includeForks).

**Comment by Justgonc** [comment]
Sure
